CREATE OR ALTER PROCEDURE dbo.SP_RelayPulses_DOLDUR
    @Id bigint
AS
BEGIN
    SET NOCOUNT ON;
    SET ARITHABORT ON;
    SET ANSI_WARNINGS ON;
    SET ANSI_PADDING ON;
    SET CONCAT_NULL_YIELDS_NULL ON;
    SET NUMERIC_ROUNDABORT OFF;

    SELECT * FROM dbo.RelayPulses WHERE Id=@Id;
END

