CREATE OR ALTER PROCEDURE dbo.SP_RelayPulses_AKTIF_KAYIT_VAR_MI
    @MakineId int=NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET ARITHABORT ON;
    SET ANSI_WARNINGS ON;
    SET ANSI_PADDING ON;
    SET CONCAT_NULL_YIELDS_NULL ON;
    SET NUMERIC_ROUNDABORT OFF;

    SELECT CAST(CASE WHEN EXISTS(SELECT 1 FROM dbo.RelayPulses WHERE PulseAktif=1 AND (@MakineId IS NULL OR MakineId=@MakineId)) THEN 1 ELSE 0 END AS bit);
END

