//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ProfilDuzenle
{
    protected global::System.Web.UI.WebControls.Image imgProfil;
    protected global::System.Web.UI.WebControls.FileUpload fuProfilResmi;
    protected global::System.Web.UI.WebControls.TextBox txtAd;
    protected global::System.Web.UI.WebControls.TextBox txtSoyad;
    protected global::System.Web.UI.WebControls.TextBox txtTelefon;
    protected global::System.Web.UI.WebControls.TextBox txtMail;
    protected global::System.Web.UI.WebControls.TextBox txtMevcutSifre;
    protected global::System.Web.UI.WebControls.TextBox txtYeniSifre;
    protected global::System.Web.UI.WebControls.TextBox txtYeniSifreTekrar;
    protected global::System.Web.UI.WebControls.Button btnKaydet;
}
